services:

  postgres:
    image: postgres:17
    container_name: lab-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  mage:
    build: .
    container_name: lab-mage

    depends_on:
      postgres:
        condition: service_healthy

    env_file:
      - .env

    environment:
      USER_CODE_PATH: /home/src/lab_project

    ports:
      - "6789:6789"

    volumes:
      - .:/home/src

    command: /app/run_app.sh mage start lab_project

volumes:
  pgdata: